### PR TITLE
Apply new design to tdwg.github.io/chrono

### LINKED ISSUE #36: Update tdwg.github.io/chrono/ to make use of new TDWG branding
https://www.tdwg.org now makes us of Jekyll and the new TDWG branding (see https://github.com/tdwg/website/pull/479). The Chronometric Age Extension website (https://tdwg.github.io/chrono/) does not and should be updated. Luckily it already makes use of Jekyll, so it is mainly changing theme and some layouts.

- [x] Update `_config.yml` to e.g. make use of `remote_theme: tdwg/petridish`
- [x] Move navigation to `_data`
- [x] Verify/update frontmatter of all pages
- [x] Test site locally
- [x] Once dwc.tdwg.org, ac.tdwg.org and tdwg.github.com/chrono are updated, remove redirect for `https://www.tdwg.org/theme/*` (@MattBlissett)

I am happy to implement all this, but can't promise when.

### PR DESCRIPTION
**Pull request by peterdesmet**
Cf. https://github.com/tdwg/dwc/pull/429, closes #36.

@tucotuco note two remarks I left in the commits, regarding:
1. Simplifying the navbar (not mimicking the Darwin Core navbar)
2. Whether the note (light blue in screenshot below) should stay

I also noticed some hidden `<!-- notes -->` regarding updating the url to https://chrono.tdwg.org, but I notice that has not (yet?) been implemented. Is that still a plan?

Chronometric-Age-Extension

### CODE REVIEW

**Comment by tucotuco** [comment]
For this one we should take the opportunity to update that page and fix an error. The whole NOTE paragraph should be omitted and the period following "to determine them" removed.

**Comment by peterdesmet** [comment]
It’s probably easiest if you make this correction yourself in `docs/index.md` on this branch.

**Comment by tucotuco** [comment]
> I also noticed some hidden `<!-- notes -->` regarding updating the url to https://chrono.tdwg.org, but I notice that has not (yet?) been implemented. Is that still a plan?

@peterdesmet I don't see those notes. It would be good to use that pattern for consistency, but no one has had any trouble, or least have not complained about it, to I think that unless it is something someone can take care of easily, it doesn't have much priority.

**Comment by peterdesmet** [comment]
Those notes are in the README. Up to you if you want to remove them. 😊

**Comment by tucotuco** [comment]
OK. Not now.

**Pull request merged**
