### PR TITLE
Changes in configuration

### PR DESCRIPTION
**Pull request by baskaufs**
Made these changes:
1. Changed the base name in config to use new subdomain. Hopefully this will get it to pick up the site theme again.
2. Modified the menus so that they will appear to be the same as on the DwC website. This will simulate a single Darwin Core website

### CODE REVIEW

**Comment by baskaufs** [comment]
I don't have push access, so can't assign reviewers. @tucotuco, can you look this over and merge if appropriate?

**Comment by tucotuco** [comment]
I merged it, but it does not seem to have picked up the site theme.

**Comment by tucotuco** [comment]
Ah, got a page build error from GitHub...

The page build failed for the `master` branch with the following error:

Page build failed. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#troubleshooting-build-errors.

For information on troubleshooting Jekyll see:

  https://docs.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can submit a request at https://support.github.com/contact?page_build_id=481120924&repo_id=108569993&tags=dotcom-pages

**Comment by baskaufs** [comment]
Yeah, I was watching the deployments at https://github.com/tdwg/chrono/deployments/github-pages and saw that it didn't build. I've had deployments fail like this before and build after making a trivial change and forcing it to redeploy. You could try that (add a space someplace at the bottom of a page and push). But if that doesn't work, we may need to get @peterdesmet to take a look.

**Comment by peterdesmet** [comment]
I see the site has been build at https://chrono.tdwg.org/ but there are css issues. Will try to fix that.

**Comment by baskaufs** [comment]
I also see that the DwC site does not have a base URL in the _config.yaml . I don't know if that makes any difference. I changed this one to "/".

**Comment by MattBlissett** [comment]
I think I've fixed it in the same way Peter fixed https://camtrap-dp.tdwg.org/

**Comment by peterdesmet** [comment]
Yes, looks good, site renders ok: https://chrono.tdwg.org/

**Comment by tucotuco** [comment]
Thanks everyone.

**Comment by peterdesmet** [comment]
[Looking at Darwin Core](https://github.com/tdwg/dwc/blob/b3b6c9eab6cfa2e01bea207839294a1680c5f6a3/docs/_config.yml#L3), I think I was wrong and we can just remove `baseurl` altogether. I will try that for this repo and see the effect. If ok, I'll update camtrap dp too

**Comment by baskaufs** [comment]
Cool!

The navigation menus look pretty seamless now. The only thing is that "Home" disappears when viewing the chrono pages. I've changed that in https://github.com/tdwg/chrono/pull/44 but I'm not sure if "home" should go to the chrono or dwc home.

**Comment by peterdesmet** [comment]
Note: `baseurl` can be safely removed (and it has)

**Pull request merged**
